### ISSUE TITLE
FEATURE REQUEST: Customize drawable for dots in timeline view

### ISSUE THREAD

**Issue by iamdeadman** [sangcomz/StickyTimeLine#10]
Hi, 

Is there a way to customize / replace the drawable for dots in timelive view. 

I can see in the "getHeaderView" method it currently uses a static image for each indicator in timeline. 

If there is no such function available to change / customize the icons in the timeline at this time, 
can you please update the project or help me submit a PR for this feature. 

TIA

Best,
Harshit

**Comment by carohauta** [comment]
I actually had something like this implemented. Added a PR #12

**Comment by iamdeadman** [comment]
+1, this should work in case we are using one drawable for each section header. 

Can we also extend it somehow so that we can use / load custom drawables for each header created ?

**Comment by sangcomz** [comment]
same issue #16 

It will be updated to the next version.
