### ISSUE TITLE
Failed linking file resources.

### ISSUE THREAD

**Issue by salime45** [sangcomz/StickyTimeLine#11]
I am implementing this library in my app, the only problem come when i try to change the color in the xml.

I get the error  " failed linking file resources. " 

    <xyz.sangcomz.stickytimelineview.TimeLineRecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:sectionCircleColor="#565656"
        />

Thera any way to change the color programatically? or some import ?

Thanks

**Comment by mabsou** [comment]
+1 I have the same problem using v0.0.19

**Comment by MahdiPishguy** [comment]
i get this error after sync project:


```
Android resource linking failed
Output:  D:\Projects\Android\materialx-21\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1417: error: resource android:attr/fontVariationSettings not found.
D:\Projects\Android\materialx-21\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1418: error: resource android:attr/ttcIndex not found.
error: failed linking references.
```

**Comment by sangcomz** [comment]
use androidX? @MahdiPishguy 
use Vector Image? @salime45

**Comment by MahdiPishguy** [comment]
@sangcomz no, i don't use androidX

**Comment by sangcomz** [comment]
um... i see i will check!

**Comment by sangcomz** [comment]
OMG..! :dizzy_face:

The README.MD document is incorrect.
I'll fix it right away.
I am sorry.
