### ISSUE TITLE
flicker header view

### ISSUE THREAD

**Issue by sangcomz** [sangcomz/StickyTimeLine#17]

**Comment by LeeOhHyung** [comment]
How can I reproduce this issue?

**Comment by sangcomz** [comment]
When scrolling, the header flickered.
It may have been fixed by changing a few other features, so let me check if the same problem occurs in the current version.

**Comment by preludezdev** [comment]
Flickering issue still exists in current version but I can't find when it exactly happens.

**Comment by propylabc** [comment]
When you scroll slowly when two headlines move, the title will blink when the first one is gone.
