### ISSUE TITLE
Section Background Bug

### ISSUE THREAD

**Issue by ehdrms2034** [sangcomz/StickyTimeLine#19]
in api version 21, section background default color doesn't match parent's background color.
for example, look at this picture 
<img width="347" alt="스크린샷 2019-10-14 오후 5 04 05" src="https://user-images.githubusercontent.com/37145713/66736732-00af1700-eea5-11e9-8155-b958d38723ae.png">

but there aren't bug in api 24~

**Comment by preludezdev** [comment]
I found that old version like api 21, default background color is #EEEEEE and it changes to #F9F9F9 later api like 24 or above. So, it looks like we have to handle the background color value setting based on api level.

**Comment by ehdrms2034** [comment]
oh thx,
so i am solving it
