### ISSUE TITLE
New ection overlapping the last item before section.

### ISSUE THREAD

**Issue by KaanRF** [sangcomz/StickyTimeLine#21]
**Describe the bug**
New section background is overlapping the before item last item.

![image](https://user-images.githubusercontent.com/3770937/68546139-9ecec800-03e4-11ea-81db-96ab1668a5ec.png)

Maybe there is already solution for it but I could not figure it out. 

My recycler view model --> 

`<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:cardBackgroundColor="@color/white"
    app:cardCornerRadius="@dimen/general_view_radius_margin">`

**Comment by niloofar92** [comment]
i have this issue too ... please help me anyone
![6b6d5eec-0ac8-49a7-8e9f-8d187330db82](https://user-images.githubusercontent.com/10316316/72207351-9ad72900-34ad-11ea-82f6-2835e41305a8.jpg)

**Comment by niloofar92** [comment]
> **Describe the bug**
> New section background is overlapping the before item last item.
> 
> ![image](https://user-images.githubusercontent.com/3770937/68546139-9ecec800-03e4-11ea-81db-96ab1668a5ec.png)
> 
> Maybe there is already solution for it but I could not figure it out.
> 
> My recycler view model -->
> 
> `<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" android:layout_width="match_parent" android:layout_height="wrap_content" app:cardBackgroundColor="@color/white" app:cardCornerRadius="@dimen/general_view_radius_margin">`

did you solve it? please share your solution..

**Comment by KaanRF** [comment]
> > **Describe the bug**
> > New section background is overlapping the before item last item.
> > ![image](https://user-images.githubusercontent.com/3770937/68546139-9ecec800-03e4-11ea-81db-96ab1668a5ec.png)
> > Maybe there is already solution for it but I could not figure it out.
> > My recycler view model -->
> > `<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" android:layout_width="match_parent" android:layout_height="wrap_content" app:cardBackgroundColor="@color/white" app:cardCornerRadius="@dimen/general_view_radius_margin">`
> 
> did you solve it? please share your solution..

Sorry I forgot the share solution,

The issue has been fixed when I implement callback to my recyclver view adapter. 

You can see below my sample implementation. 

```
public class TransactionAdapter extends ListAdapter<EntityHelper, TransactionAdapter.TransactionHolder>
        implements VerticalSectionItemDecoration.SectionCallback, Filterable {
```


```
    @Override public boolean isSection(int position) {

        if (position == RecyclerView.NO_POSITION) {
            return false;
        }
        boolean result = position == 0 || getItem( position ).getTransaction().getMonthOfTimeStamp() !=
                getItem( position - 1 ).getTransaction().getMonthOfTimeStamp() /*&&
                        getItem( position ).getTransaction().getTimeStamp().getYear() !=
                                getItem( position - 1 ).getTransaction().getTimeStamp().getYear()*/;

        return result;
    }
```

```

    @Override public SectionInfo getSectionHeader(int position) {
        DateFormat dateFormat = new SimpleDateFormat( "MM/yyyy" );
        Drawable drawable = null;
        if (position == RecyclerView.NO_POSITION) {
            return null;
        }
        return new SectionInfo( dateFormat.format( getItem( position ).getTransaction().getTimeStamp() ), message,
                drawable );
    }
```

**Comment by KaanRF** [comment]
![image](https://user-images.githubusercontent.com/3770937/73452716-86cf6a80-437b-11ea-9365-a7ba6783cace.png)

**Comment by niloofar92** [comment]
@KaanRF  thanks for your answering ... i implement your solution but all items stickd together !

![sample](https://user-images.githubusercontent.com/10316316/73518972-f2194b00-4414-11ea-992c-bb3e04494f0b.png)

**Comment by KaanRF** [comment]
Could you please also share your code ? if it is not problem for you ?

**Comment by KaanRF** [comment]
> @KaanRF thanks for your answering ... i implement your solution but all items stickd together !
> 
> ![sample](https://user-images.githubusercontent.com/10316316/73518972-f2194b00-4414-11ea-992c-bb3e04494f0b.png)

Could you please also share your code ? if it is not problem for you ?
