### ISSUE TITLE
i cant use this library for java project without migrate to androidx

### ISSUE THREAD

**Issue by niloofar92** [sangcomz/StickyTimeLine#24]
i wanna use this good library for my android-java project without migrating to androidx.. how i can?? 
seems version 0.0.19 isn't for java project and version 0.0.20 is for androidx project 
please guide me

**Comment by sangcomz** [comment]
You can use version 0.0.19.
https://github.com/sangcomz/StickyTimeLine#javaexampleactivityjava
Did you check this?

If it doesn't work with version 0.0.19, please let me know where the error occurs. Thank you.

**Comment by niloofar92** [comment]
> You can use version 0.0.19.
> https://github.com/sangcomz/StickyTimeLine#javaexampleactivityjava
> Did you check this?
> 
> If it doesn't work with version 0.0.19, please let me know where the error occurs. Thank you.

yes , I checked it first and i used 0.0.19 version in my code but it failed and when i added kotlin configuration to my project it work!!
i want to use that without adding kotlin...
