### ISSUE TITLE
some cards are shown not complete 

### ISSUE THREAD

**Issue by niloofar92** [sangcomz/StickyTimeLine#25]
@sangcomz  you see on the picture, the forth top are overlapping with before one
please help me...

![6b6d5eec-0ac8-49a7-8e9f-8d187330db82](https://user-images.githubusercontent.com/10316316/72279858-474f1180-364c-11ea-9b75-6c1c0569af6d.jpg)

**Comment by sangcomz** [comment]
Is the height of each item different?

Can you show me the code that reproduces this issue?

**Comment by niloofar92** [comment]
> Is the height of each item different?
> 
> Can you show me the code that reproduces this issue?

thanks for answering..
about first question, i should say that the height of all item is same and look like the last complete item that you see.
my code :

`

 private void InitEventList(JsonElement data) {
        List<EventLog> dataList = Helper.Parse.GetArrayObjectFromJson(data, EventLog[].class);
        eventLogList.setLayoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
        eventLogList.setItemAnimator(new DefaultItemAnimator());
        eventLogList.setNestedScrollingEnabled(true);
        EventLogAdapter adapter = new EventLogAdapter(dataList);
        eventLogList.addItemDecoration(getSectionCallback(dataList));
        eventLogList.setAdapter(adapter);
    }


    private RecyclerSectionItemDecoration.SectionCallback getSectionCallback(final List<EventLog> eventList) {

        int count = eventLogList.getItemDecorationCount();
        if (count  > 0)
            eventLogList.removeItemDecorationAt(count  - 1);

        return new RecyclerSectionItemDecoration.SectionCallback() {

            @Nullable
            @Override
            public SectionInfo getSectionHeader(int position) {
                EventLog event = eventList.get(position);
                Drawable dot;
                switch (event.getAttributeName()) {
                    case "وضعیت دستگاه": {
                        dot = activeState;
                        break;
                    }
                    case "صدا": {
                        dot = volumeState;
                        break;
                    }
                    default: {
                        dot = other;
                    }
                }
                return new SectionInfo(event.getCreateDate(), event.getAttributeName());
            }

            @Override
            public boolean isSection(int position) {
                if (eventList.size() > 0)
                    return !eventList.get(position).getCreateDate().equals(eventList.get(position - 1).getCreateDate());
                else
                    return false;
            }
        };
    }

`

**Comment by niloofar92** [comment]
> Is the height of each item different?
> 
> Can you show me the code that reproduces this issue?

@sangcomz @carohauta @ehdrms2034 
please answer me ... I'm in hurry .
if you know that problem doesn't go away easily please don't leave me at waiting so i should to solve my problem in other way

**Comment by vonclutch** [comment]
Just go for jitpack and get the fix branch

[jitpack](https://jitpack.io/#sangcomz/StickyTimeLine/feature~feat_horizontal_sample_app_and_fix-SNAPSHOT)

**Comment by sangcomz** [comment]
Sorry for not being able to respond quickly.
I can solve this problem this weekend.
And if I give it as executable code, I can solve it faster.
@niloofar92

**Comment by niloofar92** [comment]
> Sorry for not being able to respond quickly.
> I can solve this problem this weekend.
> And if I give it as executable project, I can solve it faster.
> @niloofar92

thanks so much ..
i created sample project of that issue in this link https://1drv.ms/u/s!Aq639DpozJOec7V9DoqRhKChLls?e=ogrZNQ

**Comment by niloofar92** [comment]
Three days have passed from the weekend and i dont receive answer ...
your support are very very bad

**Comment by sangcomz** [comment]
I'm sorry, I'll take care of it quickly. @niloofar92

**Comment by sangcomz** [comment]
```
    private ArrayList<EventLog> getEventList() {
        ArrayList<EventLog> eventLogs = new ArrayList<>();

        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("وضعیت دستگاه", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("صدا", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("صدا", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("صدا", "2", "3", "4", "5", "6", "7", "8", "9"));
        eventLogs.add(new EventLog("صدا", "2", "3", "4", "5", "6", "7", "8", "9"));

        return eventLogs;
    }
```
The api you gave me didn't work, so I created a dataset like this, but I can't reproduce the error. What values ​​should I put in?

## My result
![image](https://user-images.githubusercontent.com/10647548/73361577-8b970e80-42e8-11ea-98c5-23c852dd19cc.png)

**Comment by KaanRF** [comment]
Please refer the solution in --> https://github.com/sangcomz/StickyTimeLine/issues/21 

I hope it helps.

**Comment by niloofar92** [comment]
@sangcomz  you should insert more data .. as you see , in your picture that you upload, the sixth  card have problem and not complete view

![73361577-8b970e80-42e8-11ea-98c5-23c852dd19cc](https://user-images.githubusercontent.com/10316316/73519787-3a396d00-4417-11ea-8ac0-25adaaa8c3f0.png)

**Comment by sangcomz** [comment]
Okay. I'll put more items.

**Comment by sangcomz** [comment]
@niloofar92 
It was a problem because I put the wrong data.

## Result
![image](https://user-images.githubusercontent.com/10647548/73593859-b634d180-454b-11ea-9585-420accca5356.png)

I think the implementation of isSection is wrong.
Can you provide me with a real dataset?
