### ISSUE TITLE
sectionLineColor, sectionCircleColor Not found when trying to change from xml

### ISSUE THREAD

**Issue by lanrehnics** [sangcomz/StickyTimeLine#5]
Error:error: attribute 'com.bla.bla:sectionCircleColor' not found.
Error:error: attribute 'com.bla.bla:sectionLineColor' not found.
Error:attribute 'com.bla.bla:sectionCircleColor' not found.
Error:attribute 'com.bla.bla:sectionLineColor' not found.
Error:failed linking file resources.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by sangcomz** [comment]
Could you give me more information?

**Comment by lanrehnics** [comment]
Am trying to 
sectionLineColor="#565656"
sectionCircleColor="#565656"

from xml

<xyz.sangcomz.stickytimelineview.TimeLineRecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:sectionLineColor="#565656"
        app:sectionCircleColor="#565656"
        android:layout_below="@+id/toolbar" />

**Comment by sangcomz** [comment]
@lanrehnics 

There was a problem with library dependency.

Check version 0.0.16.

Please let me know if you have any other problems.

Thank you!
