### ISSUE TITLE
In list extra spaces added between items, while loading the data from web service.

### ISSUE THREAD

**Issue by dhara95** [sangcomz/StickyTimeLine#6]
I have implemented your library in my project which is written in java language. In my project  there is need to call data from web service so 1st time when I call web service at that time data properly shown but when I call  web service 2nd time for more data at that time data is displayed in the list with extra space in between the items, extra space in between items and headers as well as width of the item is also changed which is shown in below picture.
Can you help me to solve this problem
Thanking you in advance

Properly shows data when 1st time I call data from web service 
![display_proper_data](https://user-images.githubusercontent.com/13658279/40073867-b7024628-5895-11e8-983c-97552146309e.png)

Extra spaces is added in list when 2nd time I call data from web service
![extra_space_data_1](https://user-images.githubusercontent.com/13658279/40073965-f2a32454-5895-11e8-9b39-351c755db72d.png)
![extra_space_data_2](https://user-images.githubusercontent.com/13658279/40073969-f910bb30-5895-11e8-97ff-003c27a5ff48.png)
![extra_space_data_3](https://user-images.githubusercontent.com/13658279/40073975-fe71388e-5895-11e8-8b24-2d83fcb5c1cd.png)

**Comment by sangcomz** [comment]
@dhara95 
Could you show me the code implemented in RecyclerSectionItemDecoration.SectionCallback?

**Comment by dhara95** [comment]
private RecyclerSectionItemDecoration.SectionCallback getSectionCallback(List<LeadsMapMarkers> finalLeadsMapMarkersList) {
        return new RecyclerSectionItemDecoration.SectionCallback() {
            //In your data, implement a method to determine if this is a section.
            @Override
            public boolean isSection(int i) {
                return !finalLeadsMapMarkersList.get(i).getDateGroup().equals(finalLeadsMapMarkersList.get(i - 1).getDateGroup());
            }

            //Implement a method that returns a SectionHeader.
            @Override
            public SectionInfo getSectionHeader(int i) {
                return new SectionInfo(finalLeadsMapMarkersList.get(i).getDateGroup(), "");
            }
        };
    }

**Comment by TilsonF** [comment]
for me too making swipe filling the list.

**Comment by Ekkaveli** [comment]
I had the same problem, because everytime I loaded new data I added the item decoration for my new List. As a workaround I remove the old item decoration with:

`if (timeLineRecyclerView.getItemDecorationCount() > 0)
                    timeLineRecyclerView.removeItemDecorationAt(timeLineRecyclerView.getItemDecorationCount() - 1);`

Now everythings works as expected

**Comment by sangcomz** [comment]
@dhara95 

Was not it the case comment above?
Did you solve the issue in another way?

**Comment by sueysok** [comment]
> I had the same problem, because everytime I loaded new data I added the item decoration for my new List. As a workaround I remove the old item decoration with:
> 
> ```
> int count = tlRecyclerView.getItemDecorationCount();
> if (count  > 0)       
>    tlRecyclerView.removeItemDecorationAt(count  - 1);
> ```
> 
> Now everythings works as expected

it is useful for me

**Comment by faustodc** [comment]
Perhaps we should add a method to clear the whole list? or notify of a new dataset?
