### ISSUE TITLE
First Element Header Hiding..

### ISSUE THREAD

**Issue by oguzhanozdemir** [sangcomz/StickyTimeLine#7]
Hi,

In my list first element not showing in TimeLine, when I drag a little top it shows.
How can I fit it?

![hata](https://user-images.githubusercontent.com/5834722/41034426-31e84376-6992-11e8-92c4-2ce9d9a3b3f1.png)

**Comment by sangcomz** [comment]
Are you using margin in root view in item.xml?

If there is a margin, remove the margin and try it.

**Comment by oguzhanozdemir** [comment]
Yeah, I removed but didn't change.
After, I deleted all components, only use this, removed margins, it's work 👍 :)

Thank you :)
